// All countries
// length 252
export   const  Countries = [
    {"name":"Afghanistan","code":"AF","id":1,"phone":93,"symbol":"؋","capital":"Kabul","currency":"AFN","continent":"Asia","continent_code":"AS","alpha_3":"AFG"},
    {"name":"Aland Islands","code":"AX","id":2,"phone":358,"symbol":"€","capital":"Mariehamn","currency":"EUR","continent":"Europe","continent_code":"EU","alpha_3":"ALA"},
    {"name":"Albania","code":"AL","id":3,"phone":355,"symbol":"Lek","capital":"Tirana","currency":"ALL","continent":"Europe","continent_code":"EU","alpha_3":"ALB"},
    {"name":"Algeria","code":"DZ","id":4,"phone":213,"symbol":"دج","capital":"Algiers","currency":"DZD","continent":"Africa","continent_code":"AF","alpha_3":"DZA"},
    {"name":"American Samoa","code":"AS","id":5,"phone":1684,"symbol":"$","capital":"Pago Pago","currency":"USD","continent":"Oceania","continent_code":"OC","alpha_3":"ASM"},
    {"name":"Andorra","code":"AD","id":6,"phone":376,"symbol":"€","capital":"Andorra la Vella","currency":"EUR","continent":"Europe","continent_code":"EU","alpha_3":"AND"},
    {"name":"Angola","code":"AO","id":7,"phone":244,"symbol":"Kz","capital":"Luanda","currency":"AOA","continent":"Africa","continent_code":"AF","alpha_3":"AGO"},
    {"name":"Anguilla","code":"AI","id":8,"phone":1264,"symbol":"$","capital":"The Valley","currency":"XCD","continent":"North America","continent_code":"NA","alpha_3":"AIA"},
    {"name":"Antarctica","code":"AQ","id":9,"phone":672,"symbol":"$","capital":"Antarctica","currency":"AAD","continent":"Antarctica","continent_code":"AN","alpha_3":"ATA"},
    {"name":"Antigua and Barbuda","code":"AG","id":10,"phone":1268,"symbol":"$","capital":"St. John's","currency":"XCD","continent":"North America","continent_code":"NA","alpha_3":"ATG"},
    {"name":"Argentina","code":"AR","id":11,"phone":54,"symbol":"$","capital":"Buenos Aires","currency":"ARS","continent":"South America","continent_code":"SA","alpha_3":"ARG"},
    {"name":"Armenia","code":"AM","id":12,"phone":374,"symbol":"֏","capital":"Yerevan","currency":"AMD","continent":"Asia","continent_code":"AS","alpha_3":"ARM"},
    {"name":"Aruba","code":"AW","id":13,"phone":297,"symbol":"ƒ","capital":"Oranjestad","currency":"AWG","continent":"North America","continent_code":"NA","alpha_3":"ABW"},
    {"name":"Australia","code":"AU","id":14,"phone":61,"symbol":"$","capital":"Canberra","currency":"AUD","continent":"Oceania","continent_code":"OC","alpha_3":"AUS"},
    {"name":"Austria","code":"AT","id":15,"phone":43,"symbol":"€","capital":"Vienna","currency":"EUR","continent":"Europe","continent_code":"EU","alpha_3":"AUT"},
    {"name":"Azerbaijan","code":"AZ","id":16,"phone":994,"symbol":"m","capital":"Baku","currency":"AZN","continent":"Asia","continent_code":"AS","alpha_3":"AZE"},
    {"name":"Bahamas","code":"BS","id":17,"phone":1242,"symbol":"B$","capital":"Nassau","currency":"BSD","continent":"North America","continent_code":"NA","alpha_3":"BHS"},
    {"name":"Bahrain","code":"BH","id":18,"phone":973,"symbol":".د.ب","capital":"Manama","currency":"BHD","continent":"Asia","continent_code":"AS","alpha_3":"BHR"},
    {"name":"Bangladesh","code":"BD","id":19,"phone":880,"symbol":"৳","capital":"Dhaka","currency":"BDT","continent":"Asia","continent_code":"AS","alpha_3":"BGD"},
    {"name":"Barbados","code":"BB","id":20,"phone":1246,"symbol":"Bds$","capital":"Bridgetown","currency":"BBD","continent":"North America","continent_code":"NA","alpha_3":"BRB"},
    {"name":"Belarus","code":"BY","id":21,"phone":375,"symbol":"Br","capital":"Minsk","currency":"BYN","continent":"Europe","continent_code":"EU","alpha_3":"BLR"},
    {"name":"Belgium","code":"BE","id":22,"phone":32,"symbol":"€","capital":"Brussels","currency":"EUR","continent":"Europe","continent_code":"EU","alpha_3":"BEL"},
    {"name":"Belize","code":"BZ","id":23,"phone":501,"symbol":"$","capital":"Belmopan","currency":"BZD","continent":"North America","continent_code":"NA","alpha_3":"BLZ"},
    {"name":"Canada","code":"CA","id":40,"phone":1,"symbol":"$","capital":"Ottawa","currency":"CAD","continent":"North America","continent_code":"NA","alpha_3":"CAN"},
    {"name":"Egypt","code":"EG","id":66,"phone":20,"symbol":"ج.م","capital":"Cairo","currency":"EGP","continent":"Africa","continent_code":"AF","alpha_3":"EGY"},
    {"name":"El Salvador","code":"SV","id":67,"phone":503,"symbol":"$","capital":"San Salvador","currency":"USD","continent":"North America","continent_code":"NA","alpha_3":"SLV"},
    {"name":"Equatorial Guinea","code":"GQ","id":68,"phone":240,"symbol":"FCFA","capital":"Malabo","currency":"XAF","continent":"Africa","continent_code":"AF","alpha_3":"GNQ"},
    {"name":"Eritrea","code":"ER","id":69,"phone":291,"symbol":"Nfk","capital":"Asmara","currency":"ERN","continent":"Africa","continent_code":"AF","alpha_3":"ERI"},
    {"name":"Estonia","code":"EE","id":70,"phone":372,"symbol":"€","capital":"Tallinn","currency":"EUR","continent":"Europe","continent_code":"EU","alpha_3":"EST"},
    {"name":"Ethiopia","code":"ET","id":71,"phone":251,"symbol":"Nkf","capital":"Addis Ababa","currency":"ETB","continent":"Africa","continent_code":"AF","alpha_3":"ETH"},
    {"name":"Iceland","code":"IS","id":102,"phone":354,"symbol":"kr","capital":"Reykjavik","currency":"ISK","continent":"Europe","continent_code":"EU","alpha_3":"ISL"},
    {"name":"India","code":"IN","id":103,"phone":91,"symbol":"₹","capital":"New Delhi","currency":"INR","continent":"Asia","continent_code":"AS","alpha_3":"IND"},
    {"name":"Indonesia","code":"ID","id":104,"phone":62,"symbol":"Rp","capital":"Jakarta","currency":"IDR","continent":"Asia","continent_code":"AS","alpha_3":"IDN"},
    {"name":"Iran, Islamic Republic of","code":"IR","id":105,"phone":98,"symbol":"﷼","capital":"Tehran","currency":"IRR","continent":"Asia","continent_code":"AS","alpha_3":"IRN"},
    {"name":"Iraq","code":"IQ","id":106,"phone":964,"symbol":"د.ع","capital":"Baghdad","currency":"IQD","continent":"Asia","continent_code":"AS","alpha_3":"IRQ"},
    {"name":"Ireland","code":"IE","id":107,"phone":353,"symbol":"€","capital":"Dublin","currency":"EUR","continent":"Europe","continent_code":"EU","alpha_3":"IRL"},
    {"name":"Isle of Man","code":"IM","id":108,"phone":44,"symbol":"£","capital":"Douglas, Isle of Man","currency":"GBP","continent":"Europe","continent_code":"EU","alpha_3":"IMN"},
    {"name":"Israel","code":"IL","id":109,"phone":972,"symbol":"₪","capital":"Jerusalem","currency":"ILS","continent":"Asia","continent_code":"AS","alpha_3":"ISR"},
    {"name":"Italy","code":"IT","id":110,"phone":39,"symbol":"€","capital":"Rome","currency":"EUR","continent":"Europe","continent_code":"EU","alpha_3":"ITA"},
    {"name":"Jamaica","code":"JM","id":111,"phone":1876,"symbol":"J$","capital":"Kingston","currency":"JMD","continent":"North America","continent_code":"NA","alpha_3":"JAM"},
    {"name":"Japan","code":"JP","id":112,"phone":81,"symbol":"¥","capital":"Tokyo","currency":"JPY","continent":"Asia","continent_code":"AS","alpha_3":"JPN"},
    {"name":"Nepal","code":"NP","id":157,"phone":977,"symbol":"₨","capital":"Kathmandu","currency":"NPR","continent":"Asia","continent_code":"AS","alpha_3":"NPL"},
    {"name":"Netherlands","code":"NL","id":158,"phone":31,"symbol":"€","capital":"Amsterdam","currency":"EUR","continent":"Europe","continent_code":"EU","alpha_3":"NLD"},
    {"name":"Netherlands Antilles","code":"AN","id":159,"phone":599,"symbol":"NAf","capital":"Willemstad","currency":"ANG","continent":"North America","continent_code":"NA","alpha_3":"ANT"},
    {"name":"New Caledonia","code":"NC","id":160,"phone":687,"symbol":"₣","capital":"Noumea","currency":"XPF","continent":"Oceania","continent_code":"OC","alpha_3":"NCL"},
    {"name":"New Zealand","code":"NZ","id":161,"phone":64,"symbol":"$","capital":"Wellington","currency":"NZD","continent":"Oceania","continent_code":"OC","alpha_3":"NZL"},
    {"name":"Nicaragua","code":"NI","id":162,"phone":505,"symbol":"C$","capital":"Managua","currency":"NIO","continent":"North America","continent_code":"NA","alpha_3":"NIC"},
    {"name":"Niger","code":"NE","id":163,"phone":227,"symbol":"CFA","capital":"Niamey","currency":"XOF","continent":"Africa","continent_code":"AF","alpha_3":"NER"},
    {"name":"Nigeria","code":"NG","id":164,"phone":234,"symbol":"₦","capital":"Abuja","currency":"NGN","continent":"Africa","continent_code":"AF","alpha_3":"NGA"},
    {"name":"Romania","code":"RO","id":184,"phone":40,"symbol":"lei","capital":"Bucharest","currency":"RON","continent":"Europe","continent_code":"EU","alpha_3":"ROM"},
    {"name":"Russian Federation","code":"RU","id":185,"phone":70,"symbol":"₽","capital":"Moscow","currency":"RUB","continent":"Asia","continent_code":"AS","alpha_3":"RUS"},
    {"name":"Rwanda","code":"RW","id":186,"phone":250,"symbol":"FRw","capital":"Kigali","currency":"RWF","continent":"Africa","continent_code":"AF","alpha_3":"RWA"},
    {"name":"Saint Barthelemy","code":"BL","id":187,"phone":590,"symbol":"€","capital":"Gustavia","currency":"EUR","continent":"North America","continent_code":"NA","alpha_3":"BLM"},
    {"name":"Saint Helena","code":"SH","id":188,"phone":290,"symbol":"£","capital":"Jamestown","currency":"SHP","continent":"Africa","continent_code":"AF","alpha_3":"SHN"},
    {"name":"Saint Kitts and Nevis","code":"KN","id":189,"phone":1869,"symbol":"$","capital":"Basseterre","currency":"XCD","continent":"North America","continent_code":"NA","alpha_3":"KNA"},
    {"name":"Saint Lucia","code":"LC","id":190,"phone":1758,"symbol":"$","capital":"Castries","currency":"XCD","continent":"North America","continent_code":"NA","alpha_3":"LCA"},
    {"name":"Saint Martin","code":"MF","id":191,"phone":590,"symbol":"€","capital":"Marigot","currency":"EUR","continent":"North America","continent_code":"NA","alpha_3":"MAF"},
    {"name":"Saint Pierre and Miquelon","code":"PM","id":192,"phone":508,"symbol":"€","capital":"Saint-Pierre","currency":"EUR","continent":"North America","continent_code":"NA","alpha_3":"SPM"},
    {"name":"Saint Vincent and the Grenadines","code":"VC","id":193,"phone":1784,"symbol":"$","capital":"Kingstown","currency":"XCD","continent":"North America","continent_code":"NA","alpha_3":"VCT"},
    {"name":"Samoa","code":"WS","id":194,"phone":684,"symbol":"SAT","capital":"Apia","currency":"WST","continent":"Oceania","continent_code":"OC","alpha_3":"WSM"},
    {"name":"San Marino","code":"SM","id":195,"phone":378,"symbol":"€","capital":"San Marino","currency":"EUR","continent":"Europe","continent_code":"EU","alpha_3":"SMR"},
    {"name":"Sao Tome and Principe","code":"ST","id":196,"phone":239,"symbol":"Db","capital":"Sao Tome","currency":"STD","continent":"Africa","continent_code":"AF","alpha_3":"STP"},
    {"name":"Saudi Arabia","code":"SA","id":197,"phone":966,"symbol":"﷼","capital":"Riyadh","currency":"SAR","continent":"Asia","continent_code":"AS","alpha_3":"SAU"},
    {"name":"Senegal","code":"SN","id":198,"phone":221,"symbol":"CFA","capital":"Dakar","currency":"XOF","continent":"Africa","continent_code":"AF","alpha_3":"SEN"},
    {"name":"Serbia","code":"RS","id":199,"phone":381,"symbol":"din","capital":"Belgrade","currency":"RSD","continent":"Europe","continent_code":"EU","alpha_3":"SRB"},
    {"name":"Serbia and Montenegro","code":"CS","id":200,"phone":381,"symbol":"din","capital":"Belgrade","currency":"RSD","continent":"Europe","continent_code":"EU","alpha_3":"SCG"},
    {"name":"Sierra Leone","code":"SL","id":202,"phone":232,"symbol":"Le","capital":"Freetown","currency":"SLL","continent":"Africa","continent_code":"AF","alpha_3":"SLE"},
    {"name":"Singapore","code":"SG","id":203,"phone":65,"symbol":"$","capital":"Singapur","currency":"SGD","continent":"Asia","continent_code":"AS","alpha_3":"SGP"},
    {"name":"Sint Maarten","code":"SX","id":204,"phone":1,"symbol":"ƒ","capital":"Philipsburg","currency":"ANG","continent":"North America","continent_code":"NA","alpha_3":"SXM"},
    {"name":"Slovakia","code":"SK","id":205,"phone":421,"symbol":"€","capital":"Bratislava","currency":"EUR","continent":"Europe","continent_code":"EU","alpha_3":"SVK"},
    {"name":"Slovenia","code":"SI","id":206,"phone":386,"symbol":"€","capital":"Ljubljana","currency":"EUR","continent":"Europe","continent_code":"EU","alpha_3":"SVN"},
    {"name":"Sweden","code":"SE","id":218,"phone":46,"symbol":"kr","capital":"Stockholm","currency":"SEK","continent":"Europe","continent_code":"EU","alpha_3":"SWE"},
    {"name":"Switzerland","code":"CH","id":219,"phone":41,"symbol":"CHf","capital":"Berne","currency":"CHF","continent":"Europe","continent_code":"EU","alpha_3":"CHE"},
    {"name":"Syrian Arab Republic","code":"SY","id":220,"phone":963,"symbol":"LS","capital":"Damascus","currency":"SYP","continent":"Asia","continent_code":"AS","alpha_3":"SYR"},
    {"name":"Taiwan, Province of China","code":"TW","id":221,"phone":886,"symbol":"$","capital":"Taipei","currency":"TWD","continent":"Asia","continent_code":"AS","alpha_3":"TWN"},
    {"name":"Tajikistan","code":"TJ","id":222,"phone":992,"symbol":"SM","capital":"Dushanbe","currency":"TJS","continent":"Asia","continent_code":"AS","alpha_3":"TJK"},
    {"name":"Tanzania, United Republic of","code":"TZ","id":223,"phone":255,"symbol":"TSh","capital":"Dodoma","currency":"TZS","continent":"Africa","continent_code":"AF","alpha_3":"TZA"},
    {"name":"Thailand","code":"TH","id":224,"phone":66,"symbol":"฿","capital":"Bangkok","currency":"THB","continent":"Asia","continent_code":"AS","alpha_3":"THA"},
    {"name":"United Arab Emirates","code":"AE","id":237,"phone":971,"symbol":"إ.د","capital":"Abu Dhabi","currency":"AED","continent":"Asia","continent_code":"AS","alpha_3":"ARE"},
    {"name":"United Kingdom","code":"GB","id":238,"phone":44,"symbol":"£","capital":"London","currency":"GBP","continent":"Europe","continent_code":"EU","alpha_3":"GBR"},
    {"name":"United States","code":"US","id":239,"phone":1,"symbol":"$","capital":"Washington","currency":"USD","continent":"North America","continent_code":"NA","alpha_3":"USA"},
    {"name":"United States Minor Outlying Islands","code":"UM","id":240,"phone":1,"symbol":"$","capital":"","currency":"USD","continent":"North America","continent_code":"NA","alpha_3":"UMI"},
];